# Stage 1: Build the Go Application
FROM golang:latest AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN GOOS=linux GOARCH=amd64 go build -o  futureEV

# Stage 2: Create a minimal runtime environment
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/futureEV .

# (Optional) Copy Required Documents
COPY --from=builder /app/futureevdemo-firebase-adminsdk-j5evk-a5eaec3eac.json .
COPY --from=builder /app/conf/referencetest.yml conf/reference.yml

# Non-root User: Create a non-root user to run the app
RUN adduser -D -g '' appuser
USER appuser

# Run the Application
CMD ["./futureEV"]